### ISSUE TITLE
访问chrome应用商店提示“此计算机不支持该应用。已停止安装。”

### ISSUE THREAD

**Issue by kisexu** [yaniswang/smartF5#1]
操作系统： win8 
chrome版本：27

**Comment by yaniswang** [comment]
点安装就会提示？
还是一打开就提示？

**Comment by kisexu** [comment]
一打开就提示，我下了源码，直接使用都没有问题的啊。你是不是在chrome应用商店设置了什么环境要求

**Comment by yaniswang** [comment]
你WIN8是32位还是64位？

**Comment by kisexu** [comment]
是64位的。遇到这种情况解决办法可以把chrome设置成在win7兼容模式下运行，或者更加简单地，在应用安装页面打开chrome的调试工具，把安装按钮的disabled改成enable就好安装了

**Comment by yaniswang** [comment]
这个问题只在smartF5这个插件中出现吗？
我检查了下，似乎并没有设置操作系统方面的限制。
市场后台也没找到这方面的限制。

**Comment by kisexu** [comment]
也许是用了什么特殊的权限吧。我访问其他应用不会出现这个问题。也许是chrome应用商店本身对win8支持有问题

在 2013年6月21日下午4:42，Yanis Wang notifications@github.com写道：

**Comment by yaniswang** [comment]
https://support.google.com/chrome/answer/142064?hl=zh-Hans

找到答案了，是由于WIN8系统限制，chrome只能使用 Pepper API（如 Flash、Native Client 和 Chrome PDF 查看器），而smartF5内部使用了NPAPI，因此无法使用。

网上现有的唯一解决方案和你说的一样，改为WIN7模式运行。

**Comment by kisexu** [comment]
最佳解决方案是在chrome应用商店的安装按钮上右键审查元素，然后把disabled改成enable，就可以安装了。

我看官方说明只是在chrome作为win8应用运行时会有问题，我现在是普通模式，使用这个插件是没有问题的。

最后谢谢，这个插件很给力，特别是支持file模式 O(∩_∩)O~

在 2013年6月21日下午4:52，Yanis Wang notifications@github.com写道：
